services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - "nginx-proxy"
    volumes_from:
       - "nginx-proxy"
    volumes:
       - ./certs:/etc/nginx/certs:rw
       - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        - DEFAULT_EMAIL=${email}
    networks:
      - proxy

  frontend:
    build: frontend
    container_name: frontend
    restart: unless-stopped
    expose:
        - "80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=project-mealtastic.amazingcloud.space
      - LETSENCRYPT_HOST=project-mealtastic.amazingcloud.space
      - NEXT_PUBLIC_API_URL=project-mealtastic.amazingcloud.space
      - VIRTUAL_PORT=3000
    depends_on:
      - backend

  backend:
    build: backend
    image: backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=project-mealtastic.amazingcloud.space
      - VIRTUAL_PATH=/api/
      - VIRTUAL_PORT=3001
    networks:
      - proxy
      - internal
  
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mealtastic
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    # ports:
    #   - "5432:5432" 
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   volumes:
  #     - ./data:/data

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge

volumes:
  pgdata:
