//Generated by Claude Code, 
//Prompts Used: [pasted Recipe backend code and inital recipe pages UI skeleton], integrate the backend with the frontend, using my structure
                
"use client";

import Link from "next/link";
import Image from "next/image";
import { Recipe } from "@/types";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Clock, Users, Heart, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { useRecipes } from "@/lib/hooks/useRecipes";

interface RecipeCardProps {
  recipe: Recipe;
  onSaveToggle?: () => void;
}

export default function RecipeCard({ recipe, onSaveToggle }: RecipeCardProps) {
  const { isRecipeSaved, saveRecipe, unsaveRecipe } = useRecipes();
  const [isSaved, setIsSaved] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsSaved(isRecipeSaved(recipe.id));
  }, [recipe.id, isRecipeSaved]);

  const totalTime = recipe.prep_time || 0;

  const handleSaveToggle = async (e: React.MouseEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      if (isSaved) {
        const success = await unsaveRecipe(recipe.id);
        if (success) {
          setIsSaved(false);
        }
      } else {
        const success = await saveRecipe(recipe.id);
        if (success) {
          setIsSaved(true);
        }
      }
      onSaveToggle?.();
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Link href={`/recipes/${recipe.id}`}>
      <Card className="overflow-hidden hover:shadow-lg transition-shadow cursor-pointer h-full">
        <div className="relative h-48 w-full bg-gray-200">
          {recipe.image_url ? (
            <Image
              src={recipe.image_url}
              alt={recipe.title}
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center text-gray-400">
              No Image
            </div>
          )}
          <Button
            variant="ghost"
            size="icon"
            className={`absolute top-2 right-2 rounded-full ${
              isSaved
                ? "bg-red-500 hover:bg-red-600"
                : "bg-white/80 hover:bg-white"
            }`}
            onClick={handleSaveToggle}
            disabled={isLoading}
          >
            <Heart
              className={`h-5 w-5 ${
                isSaved ? "fill-white text-white" : "text-gray-700"
              }`}
            />
          </Button>
        </div>

        <CardContent className="p-4">
          <h3 className="font-semibold text-lg mb-2 line-clamp-2">
            {recipe.title}
          </h3>

          <div className="flex gap-4 text-sm text-muted-foreground mb-3">
            {totalTime > 0 && (
              <div className="flex items-center gap-1">
                <Clock className="h-4 w-4" />
                <span>{totalTime} min</span>
              </div>
            )}
            {recipe.cached_data?.servings && (
              <div className="flex items-center gap-1">
                <Users className="h-4 w-4" />
                <span>{recipe.cached_data.servings} servings</span>
              </div>
            )}
          </div>

          <div className="flex flex-wrap gap-2">
            {recipe.cuisines && recipe.cuisines.length > 0 && (
              <Badge variant="secondary" className="text-xs bg-blue-300">
                {recipe.cuisines[0]}
              </Badge>
            )}
            {recipe.diets?.slice(0, 2).map((diet) => (
              <Badge
                key={diet}
                variant="outline"
                className="text-xs bg-green-300"
              >
                {diet}
              </Badge>
            ))}
          </div>
        </CardContent>
        <CardFooter>
          {Array.from({ length: 5 }).map((_, index) => {
            const fillPercentage =
              Math.max(0, Math.min(1, (recipe.rating || 0) - index)) * 100;

            return (
              <div key={index} className="relative inline-block">
                <Star size={16} className="text-gray-300 fill-transparent" />
                <div
                  className="absolute top-0 left-0 overflow-hidden"
                  style={{ width: `${fillPercentage}%` }}
                >
                  <Star size={16} className="text-yellow-400 fill-yellow-400" />
                </div>
              </div>
            );
          })}
        </CardFooter>
      </Card>
    </Link>
  );
}
