//generated by claude code. 
//Prompts used: "[pasted backend auth code and inital frontend UI code from /login and /register] help me synchronize authentication state throughout the whole app"
//              "I want to prevent users from accesing pages that are not login and register when not authenticated"

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/store/authStore';

export function useRequireAuth() {
  const router = useRouter();
  const { user, isLoading } = useAuthStore();

  useEffect(() => {
    if (!isLoading && !user) {
      router.push('/login');
    }
  }, [user, isLoading, router]);

  return { user, isLoading };
}

export function useRedirectIfAuthenticated(redirectTo: string = '/recipes') {
  const router = useRouter();
  const { user, isLoading } = useAuthStore();

  useEffect(() => {
    if (!isLoading && user) {
      router.push(redirectTo);
    }
  }, [user, isLoading, router, redirectTo]);

  return { user, isLoading };
}

export function useAuth() {
  return useAuthStore();
}