import { Request, Response, NextFunction } from "express";
import pool from "../db";
import * as mealPlanQuery from "../queries/mealPlanQueries";
import * as preferencesQuery from "../queries/preferencesQueries";
import * as recipesQuery from "../queries/recipesQueries";

// File initially made by Ramim who dropped the course,
// but we assume was initially generated by chatgpt
// exporting to google calendar: https://chatgpt.com/s/t_69293b3602148191806f9470f58597ab (feature dropped due to approval period from google) 

export function getWeekStart(): string {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const monday = new Date(today);
  monday.setDate(today.getDate() - ((dayOfWeek + 6) % 7));
  return monday.toISOString().split("T")[0];
}

const MEAL_TIMES: Record<string, string> = {
  breakfast: "08:00",
  lunch: "12:00",
  dinner: "18:00",
};

const WEBSITE_URL = process.env.NEXT_PUBLIC_FRONTEND_URL!;

export async function generateWeeklyMealPlan(req: Request, res: Response, next: NextFunction) {
  const userId = req.session.userId;
  if (!userId) return res.status(401).end("Unauthorized");
  let recipes: any[] = [];
  try {
    // Fetch user preferences
    const prefResult = await pool.query(preferencesQuery.getUserPreferences, [userId]);
    const preferences = prefResult.rows[0];

    // Get user's saved recipes
    let recipeQuery = recipesQuery.getUserSavedRecipes;
    const params: any[] = [userId];
    let num_params = 1;

    // Apply filters (diet, calorie range, excluded ingredients)
    if (preferences?.diet) {
      num_params++;
      recipeQuery += ` AND LOWER($${num_params}) = ANY(ARRAY(SELECT LOWER(unnest(r.diets))))`;
      params.push(preferences.diet.toLowerCase());
    }
    if (preferences?.exclude_ingredients?.length > 0) {
      num_params++;
      recipeQuery += ` AND NOT (ARRAY(SELECT jsonb_array_elements_text(r.cached_data->'ingredients')) && $${num_params}::text[])`;
      params.push(preferences.exclude_ingredients);
    }

    const recipeResult = await pool.query(recipeQuery, params);
    recipes = recipeResult.rows;
    if (recipes.length === 0) return res.status(400).json({ error: "No suitable saved recipes found." });
  } catch (err) {
    console.log("Error getting saved recipes for meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }

  const weekStart = getWeekStart();
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(mealPlanQuery.insertMealPlan, [userId, weekStart]);
    const planResult = await client.query(mealPlanQuery.getMealPlanLock, [userId, weekStart]);
    const planId = planResult.rows[0].id;

    // Generate entries (7 days × 3 meals)
    const mealTypes = ["breakfast", "lunch", "dinner"];
    const entries = [];
    const monday = new Date(weekStart);

    for (let i = 0; i < 7; i++) {
      const date = new Date(monday);
      date.setDate(monday.getDate() + i);
      const dateStr = date.toISOString().split("T")[0];

      for (const mealType of mealTypes) {
        const randomRecipe = recipes[Math.floor(Math.random() * recipes.length)];
        entries.push({ plan_id: planId, date: dateStr, meal_type: mealType, recipe_id: randomRecipe.id });
      }
    }

    await client.query(mealPlanQuery.deleteEntryWithPlanID, [planId])

    // Insert entries
    const insertPromises = entries.map(e =>
      client.query(mealPlanQuery.insertMealPlanEntry, [e.plan_id, e.date, e.meal_type, e.recipe_id])
    );
    await Promise.all(insertPromises);
    await client.query("COMMIT");

    // Return result
    res.json({ plan_id: planId, week_start: weekStart, entries });
  } catch (err) {
    await client.query("ROLLBACK");
    console.log("Error generating meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  } finally {
    client.release();
  }
}

export async function getMealPlan(req: Request, res: Response, next: NextFunction) {
  const userId = req.session.userId;
  if (!userId) return res.status(401).end("Unauthorized");
  const weekStart = req.query.week_start as string || getWeekStart();
  try {
    const result = await pool.query(mealPlanQuery.getMealPlanEntriesWithUserIDWeek, [userId, weekStart]);
    if (result.rows.length === 0) return res.status(404).json({ message: "No meal plan found for this week." });

    res.json({ week_start: weekStart, entries: result.rows });
  } catch (err) {
    console.error("Error fetching meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function updateMealPlanEntry(req: Request, res: Response, next: NextFunction) {
  const entryId = req.params.id;
  const { recipe_id } = req.body;
  if (!entryId) return res.status(400).end("Missing entry ID");
  try {
    await pool.query(mealPlanQuery.updateMealPlanEntry, [recipe_id || null, entryId]);
    res.sendStatus(200);
  } catch (err) {
    console.error("Error updating meal entry:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function deleteMealPlan(req: Request, res: Response, next: NextFunction) {
  const planId = req.params.id;
  const userId = req.session.userId;
  if (!planId || !userId) return res.status(400).end("Invalid request");
  try {
    await pool.query(mealPlanQuery.deleteMealPlan, [planId, userId]);
    res.sendStatus(200);
  } catch (err) {
    console.error("Error deleting meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function exportMealPlanICS(req: Request, res: Response) {
  const userId = req.session.userId;
  if (!userId) return res.status(401).end("Unauthorized");
  const weekStart = req.query.week_start as string || getWeekStart();
  try {
    const result = await pool.query(mealPlanQuery.getMealPlanEntriesWithUserIDWeek, [userId, weekStart]);

    if (result.rows.length === 0) {
      return res.status(404).json({ message: "No meal plan found" });
    }

    let ics = "";
    ics += "BEGIN:VCALENDAR\n";
    ics += "VERSION:2.0\n";
    ics += "CALSCALE:GREGORIAN\n";
    ics += "PRODID:-//Meal Planner App//EN\n";

    for (const entry of result.rows) {
      const mealTime = MEAL_TIMES[entry.meal_type];
      if (!mealTime) continue;

      const date = entry.date.toISOString().split("T")[0];
      const dtStart = `${date}T${mealTime.replace(":", "")}00`.replace(/[-:]/g, "");

      const [h, m] = mealTime.split(":");
      const endH = Number(h) + 1;
      const endHour = String(endH).padStart(2, "0");
      const dtEnd = `${date}T${endHour}${m}00`.replace(/[-:]/g, "");

      const uid = `${entry.id}@mealplanner`;

      ics += "BEGIN:VEVENT\n";
      ics += `UID:${uid}\n`;
      ics += `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z/, "")}\n`;
      ics += `DTSTART:${dtStart}\n`;
      ics += `DTEND:${dtEnd}\n`;
      ics += `SUMMARY:${escapeICS(entry.title)}\n`;
      ics += `DESCRIPTION:${escapeICS(`${WEBSITE_URL}/recipes/${entry.recipe_id}`)}\n`;
      ics += "END:VEVENT\n";
    }

    ics += "END:VCALENDAR";

    res.setHeader("Content-Type", "text/calendar; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="meal-plan.ics"`
    );

    res.send(ics);
  } catch (err) {
    console.error("Error exporting ICS:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

function escapeICS(str: string) {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}