import { Request, Response, NextFunction } from "express";
import { getGoogleCalendarClient } from "../config/googleCalendar";
import pool from "../db";
import { calendar_v3 } from "googleapis";
import * as mealPlanQuery from "../queries/mealPlanQueries";
import * as preferencesQuery from "../queries/preferencesQueries";
import * as recipesQuery from "../queries/recipesQueries";

// File initially made by Ramim who dropped the course,
// but we assume was initially generated by chatgpt

export function getWeekStart(): string {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const monday = new Date(today);
  monday.setDate(today.getDate() - ((dayOfWeek + 6) % 7));
  return monday.toISOString().split("T")[0];
}

const MEAL_TIMES = {
  breakfast: "13:00",
  lunch: "17:00",
  dinner: "23:00",
};

type MealPlanEntry = {
  title: string,
  image_url: string,
  source: string,
  id: string,
  plan_id: string,
  date: Date,
  meal_type: "breakfast" | "lunch" | "dinner",
  recipe_id: string
}

const WEBSITE_URL = process.env.NEXT_PUBLIC_FRONTEND_URL!;

export async function generateWeeklyMealPlan(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");

    const weekStart = getWeekStart();

    let planId = ""
    const checkResult = await pool.query(mealPlanQuery.getMealPlanWithUserIDWeek, [userId, weekStart]);
    if (checkResult.rows.length > 0) {
      planId = checkResult.rows[0].id;
      await pool.query(mealPlanQuery.deleteEntryWithPlanID, [planId]);
    }

    // Fetch user preferences
    const prefResult = await pool.query(preferencesQuery.getUserPreferences, [userId]);
    const preferences = prefResult.rows[0];

    // Get user's saved recipes
    let recipeQuery = recipesQuery.getUserSavedRecipes;
    const params: any[] = [userId];
    let num_params = 1;

    // Apply filters (diet, calorie range, excluded ingredients)
    if (preferences?.diet) {
      num_params++;
      recipeQuery += ` AND LOWER($${num_params}) = ANY(ARRAY(SELECT LOWER(unnest(r.diets))))`;
      params.push(preferences.diet.toLowerCase());
    }
    if (preferences?.exclude_ingredients?.length > 0) {
      num_params++;
      recipeQuery += ` AND NOT (ARRAY(SELECT jsonb_array_elements_text(r.cached_data->'ingredients')) && $${num_params}::text[])`;
      params.push(preferences.exclude_ingredients);
    }

    const recipeResult = await pool.query(recipeQuery, params);
    const recipes = recipeResult.rows;
    if (recipes.length === 0) return res.status(400).json({ error: "No suitable saved recipes found." });

    // Create meal plan record
    const planResult = await pool.query(mealPlanQuery.insertMealPlan, [userId, weekStart]);
    if (planResult.rows.length > 0) planId = planResult.rows[0].id;

    // Generate entries (7 days × 3 meals)
    const mealTypes = ["breakfast", "lunch", "dinner"];
    const entries = [];
    const monday = new Date(weekStart);

    for (let i = 0; i < 7; i++) {
      const date = new Date(monday);
      date.setDate(monday.getDate() + i);
      const dateStr = date.toISOString().split("T")[0];

      for (const mealType of mealTypes) {
        const randomRecipe = recipes[Math.floor(Math.random() * recipes.length)];
        entries.push({ plan_id: planId, date: dateStr, meal_type: mealType, recipe_id: randomRecipe.id });
      }
    }

    // Insert entries
    const insertPromises = entries.map(e =>
      pool.query(mealPlanQuery.insertMealPlanEntry, [e.plan_id, e.date, e.meal_type, e.recipe_id])
    );
    await Promise.all(insertPromises);

    // Return result
    res.json({ plan_id: planId, week_start: weekStart, entries });
  } catch (err) {
    console.error("Error generating meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function getMealPlan(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");

    const weekStart = req.query.week_start as string || getWeekStart();
    const result = await pool.query(mealPlanQuery.getMealPlanEntriesWithUserIDWeek, [userId, weekStart]);
    if (result.rows.length === 0) return res.status(404).json({ message: "No meal plan found for this week." });

    res.json({ week_start: weekStart, entries: result.rows });
  } catch (err) {
    console.error("Error fetching meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function updateMealPlanEntry(req: Request, res: Response, next: NextFunction) {
  try {
    const entryId = req.params.id;
    const { recipe_id } = req.body;
    if (!entryId) return res.status(400).end("Missing entry ID");

    await pool.query(mealPlanQuery.updateMealPlanEntry, [recipe_id || null, entryId]);

    res.sendStatus(200);
  } catch (err) {
    console.error("Error updating meal entry:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function deleteMealPlan(req: Request, res: Response, next: NextFunction) {
  try {
    const planId = req.params.id;
    const userId = req.session.userId;
    if (!planId || !userId) return res.status(400).end("Invalid request");

    await pool.query(mealPlanQuery.deleteMealPlan, [planId, userId]);

    res.sendStatus(200);
  } catch (err) {
    console.error("Error deleting meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function exportMealPlanToGoogleCalendar(req: Request, res: Response) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");

    const weekStart = req.query.week_start as string || getWeekStart();
    const result = await pool.query(mealPlanQuery.getMealPlanEntriesWithUserIDWeek, [userId, weekStart]);

    if (result.rows.length === 0)
      return res.status(404).json({ message: "No meal plan found for this week." });

    const userResult = await pool.query(
      `SELECT google_access_token, google_refresh_token FROM users WHERE id=$1;`,
      [userId]
    );
    const user = userResult.rows[0];
    if (!user?.google_refresh_token)
      return res.status(400).json({ error: "User has not connected Google Calendar." });

    const calendar = getGoogleCalendarClient({
      access_token: user.google_access_token,
      refresh_token: user.google_refresh_token,
    });

    const planId = result.rows[0].plan_id;

    const startDate = new Date(`${weekStart}T00:00:00Z`); // start of week in UTC
    const endDate = new Date(startDate.getTime() + 7 * 24 * 60 * 60 * 1000); // 7 days later

    const existingEventsRes = await calendar.events.list({
      calendarId: "primary",
      privateExtendedProperty: [`mealPlanId=${planId}`],
      timeMin: startDate.toISOString(),
      timeMax: endDate.toISOString(),
    });

    const existingEventTimes = new Map<string, calendar_v3.Schema$Event>();

    for (const ev of existingEventsRes.data.items || []) {
      if (!ev.start?.dateTime) continue;
      const startUTC = new Date(ev.start.dateTime).toISOString().replace('00.000Z', '00Z');
      existingEventTimes.set(startUTC, ev);
    }

    for (const entry of result.rows as MealPlanEntry[]) {
      const time = MEAL_TIMES[entry.meal_type];
      if (!entry.date || !time) continue;

      const dateStr = entry.date.toISOString().split("T")[0];
      const startDateTime = `${dateStr}T${time}:00Z`;

      const startDate = new Date(startDateTime);
      if (isNaN(startDate.getTime())) continue;

      const endDateTime = new Date(startDate.getTime() + 60 * 60 * 1000).toISOString();

      if (existingEventTimes.has(startDateTime)) {
        const existingEvent = existingEventTimes.get(startDateTime);
        if (existingEvent && existingEvent.summary !== entry.title) {
          await calendar.events.update({
            calendarId: "primary",
            eventId: existingEvent.id!,
            requestBody: {
              summary: entry.title,
              description: `${WEBSITE_URL}/recipes/${entry.recipe_id}`,
              start: { dateTime: startDateTime },
              end: { dateTime: endDateTime },
              extendedProperties: { private: { mealPlanId: planId } },
            },
          });
        }
        continue;
      }
      await calendar.events.insert({
        calendarId: "primary",
        requestBody: {
          summary: entry.title,
          description: `${WEBSITE_URL}/recipes/${entry.recipe_id}` || "",
          start: { dateTime: startDateTime },
          end: { dateTime: endDateTime },
          extendedProperties: { private: { mealPlanId: planId } },
        },
      });

      await new Promise(r => setTimeout(r, 150));
    }

    res.sendStatus(200);
  } catch (err) {
    console.error("Error exporting meal plan:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}
