import { Request, Response, NextFunction } from "express";
import pool from "../db";
import { getWeekStart } from "./mealPlannerController";
import * as shoppingQuery from "../queries/shoppingListQueries";
import * as mealPlanQuery from "../queries/mealPlanQueries";

// File initially made by Ramim who dropped the course,
// but we assume was initially generated by chatgpt

const VOLUME_UNITS = ["ml", "l", "pinch", "handful", "serving"];
const WEIGHT_UNITS = ["mg", "g", "kg"];

const METRIC_CONVERSIONS = {
  volume: {
    base: "ml",
    rules: [
      { unit: "l", factor: 1000 },
    ],
  },
  weight: {
    base: "g",
    rules: [
      { unit: "mg", factor: 0.001 },
      { unit: "kg", factor: 1000 },
      { unit: "pinch", factor: 0.5 },
      { unit: "handful", factor: 50 },
      { unit: "serving", factor: 100 },
    ],
  },
};

const metricUnitType = (unit: string) => {
  if (VOLUME_UNITS.includes(unit)) return "volume";
  if (WEIGHT_UNITS.includes(unit)) return "weight";
  return "other";
};

const normalizeMetricUnit = (qty: number, unit: string) => {
  const type = metricUnitType(unit);
  if (type === "other") return { qty, unit };

  const group = METRIC_CONVERSIONS[type];
  for (const rule of group.rules) {
    if (unit === rule.unit) {
      return {
        qty: qty * rule.factor,
        unit: group.base,
      };
    }
  }

  return { qty, unit };
};

export async function generateShoppingList(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");

    let { plan_id } = req.query;
    if (!plan_id) {
      const week_start = getWeekStart();
      const checkMealPlanResult = await pool.query(mealPlanQuery.getMealPlanWithUserIDWeek, [userId, week_start]);
      if (checkMealPlanResult.rows.length > 0) {
        plan_id = checkMealPlanResult.rows[0].id;
      }
      else {
        return res.status(400).end("Missing plan_id in query and no meal plan created for this week.");
      }
    }

    const entryResult = await pool.query(mealPlanQuery.getEntriesRecipeData, [plan_id]);

    if (entryResult.rows.length === 0)
      return res.status(404).json({ message: "No entries for this meal plan." });

    const existingListResult = await pool.query(shoppingQuery.getUserAndPlanShoppingList, [plan_id, userId]);

    if (existingListResult.rows.length > 0) {
      await pool.query(shoppingQuery.deleteShoppingList, [existingListResult.rows[0].id]);
    }

    const allIngredients: Record<
      string,
      { quantity: number; unit: string; category?: string }
    > = {};

    // get ingredients from all recipes in meal plan
    // their quantity, unit, and category 
    for (const row of entryResult.rows) {
      const recipeData = row.cached_data;
      const ingredients = recipeData?.extendedIngredients || [];

      for (const ing of ingredients) {
        const name = ing.name?.toLowerCase();
        if (!name) continue;

        const category = ing.aisle || null;

        const metric = ing.measures?.metric;
        if (!metric || metric.amount == null) continue;

        let qty = metric.amount;
        let unit = (metric.unitShort || "").toLowerCase();

        const key = `${name}__${unit}`;

        if (allIngredients[key]) {
          allIngredients[key].quantity += qty;
        } else {
          allIngredients[key] = { quantity: qty, unit, category };
        }
      }
    }

    // sum up the quantities using normalized units
    for (const key of Object.keys(allIngredients)) {
      const item = allIngredients[key];
      const normalized = normalizeMetricUnit(item.quantity, item.unit);
      item.quantity = normalized.qty;
      item.unit = normalized.unit;
    }

    const listResult = await pool.query(shoppingQuery.insertShoppingList, [plan_id, userId]);
    const listId = listResult.rows[0].id;

    const insertPromises = Object.entries(allIngredients).map(
      ([nameWithUnit, data]) => {
        const [name] = nameWithUnit.split("__");
        return pool.query(
          shoppingQuery.insertShoppingItem,
          [listId, name, data.quantity, data.unit, data.category]
        );
      }
    );
    await Promise.all(insertPromises);

    res.status(201).json({ list_id: listId, items: allIngredients });
  } catch (err) {
    console.error("Error generating shopping list:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function getShoppingList(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");

    const { plan_id } = req.params;
    if (!plan_id) return res.status(400).end("Missing plan_id in query");

    const result = await pool.query(shoppingQuery.getShoppingItems, [userId, plan_id]);

    res.json({ items: result.rows });
  } catch (err) {
    console.error("Error fetching shopping list:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function getShoppingLists(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    if (!userId) return res.status(401).end("Unauthorized");
    const page = req.query.page ? parseInt(req.query.page as string) : 0;
    const limit = req.query.limit ? parseInt(req.query.limit as string) : 0;

    const countResult = await pool.query(shoppingQuery.countShoppingLists, [userId]);

    const totalItems = parseInt(countResult.rows[0].total, 10);
    const totalPages = Math.ceil(totalItems / limit);

    const result = await pool.query(shoppingQuery.getShoppingLists, [userId, limit, limit * page]);

    res.json({ lists: result.rows, totalItems: totalItems, totalPages: totalPages });
  } catch (err) {
    console.error("Error fetching user shopping lists:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function updateShoppingItem(req: Request, res: Response, next: NextFunction) {
  try {
    const userId = req.session.userId;
    const itemId = req.params.id;
    const { checked, quantity } = req.body;

    if (!itemId) return res.status(400).end("Missing item ID");

    const checkShoppingItemUser = await pool.query(shoppingQuery.checkShoppingItemUser, [itemId, userId]);
    if (checkShoppingItemUser.rows.length === 0)
      return res.status(401).end("Not user's shopping list item. Unauthorized.");

    const fields: string[] = [];
    const values: any[] = [];
    let i = 1;

    if (typeof checked === "boolean") {
      fields.push(`checked = $${i++}`);
      values.push(checked);
    }

    if (quantity !== undefined) {
      fields.push(`quantity = $${i++}`);
      values.push(quantity);
    }

    if (fields.length === 0)
      return res.status(400).end("No valid fields to update");

    values.push(itemId);

    await pool.query(
      `UPDATE shopping_items SET ${fields.join(", ")} WHERE id = $${i};`,
      values
    );

    res.sendStatus(200);
  } catch (err) {
    console.error("Error updating shopping item:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function deleteShoppingList(req: Request, res: Response, next: NextFunction) {
  try {
    const listId = req.params.id;
    const userId = req.session.userId;
    if (!listId || !userId) return res.status(400).end("Invalid request");

    const checkUserResult = await pool.query(shoppingQuery.checkShoppingListUser, [listId, userId]);
    if (checkUserResult.rows.length == 0) return res.status(401).end("Not user's shopping list. Unauthorized.");
    await pool.query(shoppingQuery.deleteShoppingList, [listId]);

    res.sendStatus(200);
  } catch (err) {
    console.error("Error deleting shopping list:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}

export async function deleteShoppingItem(req: Request, res: Response, next: NextFunction) {
  try {
    const itemId = req.params.id;
    const userId = req.session.userId;
    if (!itemId || !userId) return res.status(400).end("Invalid request");

    const checkShoppingItemUser = await pool.query(shoppingQuery.checkShoppingItemUser, [itemId, userId]);
    if (checkShoppingItemUser.rows.length === 0)
      return res.status(401).end("Not user's shopping list item. Unauthorized.");

    await pool.query(shoppingQuery.deleteShoppingItem, [itemId]);

    res.sendStatus(200);
  } catch (err) {
    console.error("Error deleting shopping list item:", err);
    if (err instanceof Error) return res.status(500).end(err.message);
    return res.status(500).end(err);
  }
}
