//generated by claude code.
//Prompts used: "[pasted backend auth code and inital frontend UI code from /login and /register] help me synchronize authentication state throughout the whole app"
//              "I want to prevent users from accesing pages that are not login and register when not authenticated"

import { create } from "zustand";

interface User {
  id: string;
  email: string;
  name: string;
}

interface AuthState {
  user: User | null;
  isLoading: boolean;
  setUser: (user: User | null) => void;
  setLoading: (isLoading: boolean) => void;
  login: (user: User) => void;
  logout: () => void;
}

export const useAuthStore = create<AuthState>((set) => ({
  user: null,
  isLoading: true,

  setUser: (user) => set({ user }),
  setLoading: (isLoading) => set({ isLoading }),

  login: (user) => {
    // Store user data locally (session cookie handled by backend)
    localStorage.setItem("user", JSON.stringify(user));
    set({ user, isLoading: false });
  },

  logout: () => {
    localStorage.removeItem("user");
    set({ user: null });
  },
}));
